export const ErrorCodes = {
	REQUIRED: 'REQUIRED',
	DATA_REQUIRED: 'DATA_REQUIRED',
	DATA_NOT_OBJECT: 'DATA_NOT_OBJECT',
	UNEXPECTED_FIELD: 'UNEXPECTED_FIELD',

	NOT_STRING: 'NOT_STRING',
	NOT_NUMBER: 'NOT_NUMBER',
	NOT_NUMERIC_STRING: 'NOT_NUMERIC_STRING',
	NOT_BOOLEAN: 'NOT_BOOLEAN',
	NOT_BOOLEAN_STRING: 'NOT_BOOLEAN_STRING',
	NOT_ARRAY: 'NOT_ARRAY',
	NOT_OBJECT: 'NOT_OBJECT',
	NOT_BIGINT: 'NOT_BIGINT',
	NOT_SYMBOL: 'NOT_SYMBOL',

	NOT_EMAIL: 'NOT_EMAIL',
	NOT_URL: 'NOT_URL',
	NOT_DOMAIN: 'NOT_DOMAIN',
	NOT_NAME: 'NOT_NAME',
	NOT_FULLNAME: 'NOT_FULLNAME',
	NOT_USERNAME: 'NOT_USERNAME',
	NOT_ALPHA: 'NOT_ALPHA',
	NOT_ALPHANUMERIC: 'NOT_ALPHANUMERIC',
	NOT_PHONE: 'NOT_PHONE',
	NOT_PHONECODE: 'NOT_PHONECODE',
	NOT_OBJECTID: 'NOT_OBJECTID',
	NOT_UUID: 'NOT_UUID',
	NOT_DATE: 'NOT_DATE',
	NOT_DATEONLY: 'NOT_DATEONLY',
	NOT_TIME: 'NOT_TIME',
	NOT_IP: 'NOT_IP',

	NOT_LOWERCASE: 'NOT_LOWERCASE',
	NOT_UPPERCASE: 'NOT_UPPERCASE',

	NOT_INTEGER: 'NOT_INTEGER',
	NOT_POSITIVE: 'NOT_POSITIVE',
	NOT_NEGATIVE: 'NOT_NEGATIVE',
	NOT_NATURAL: 'NOT_NATURAL',
	NOT_WHOLE: 'NOT_WHOLE',

	LENGTH_MISMATCH: 'LENGTH_MISMATCH',
	DIGITS_MISMATCH: 'DIGITS_MISMATCH',
	TOO_SHORT: 'TOO_SHORT',
	TOO_LONG: 'TOO_LONG',
	TOO_SMALL: 'TOO_SMALL',
	TOO_LARGE: 'TOO_LARGE',
	DATE_TOO_EARLY: 'DATE_TOO_EARLY',
	DATE_TOO_LATE: 'DATE_TOO_LATE',
	NOT_EQUAL: 'NOT_EQUAL',

	DECIMAL_SIZE_MISMATCH: 'DECIMAL_SIZE_MISMATCH',
	DECIMAL_TOO_FEW: 'DECIMAL_TOO_FEW',
	DECIMAL_TOO_MANY: 'DECIMAL_TOO_MANY',
	NOT_A_NUMBER: 'NOT_A_NUMBER',

	ENUM_MISMATCH: 'ENUM_MISMATCH',
	REGEX_MISMATCH: 'REGEX_MISMATCH',

	ATLEAST_NOT_MET: 'ATLEAST_NOT_MET',
	ATMOST_EXCEEDED: 'ATMOST_EXCEEDED',

	INVALID_RULE: 'INVALID_RULE',
	INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes]

export interface ValidationDetail {
	message: string
	code: ErrorCode
}
